# Generated by Django 3.1.5 on 2021-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
