# Generated by Django 3.1.5 on 2021-01-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
