# Generated by Django 3.1.5 on 2021-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
