# Generated by Django 3.1.5 on 2021-03-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210224_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bought',
            field=models.ManyToManyField(to='products.Item'),
        ),
    ]
