# Generated by Django 3.1.5 on 2021-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_profile_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='products.Item'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bought',
            field=models.ManyToManyField(related_name='bought', to='products.Item'),
        ),
    ]
