# Generated by Django 3.1.5 on 2021-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210302_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='profile_pics'),
        ),
    ]
